### ISSUE TITLE
感谢整理

### ISSUE THREAD

**Issue by EarlWilliam** [jckling/ffxiv-resources#1]
非常全面，几乎覆盖了日常会遇到的所有场景，一时也想不到有哪里可以补充的。已经发给笨蛋萌新亲友了（咦
本来是在找Kolla部署Openstack教程参考学习的，谁会想到结局会是这样（......）希望您清CD顺...不对，早就毕业了吧？

**Comment by jckling** [comment]
其实整理得还不全面，很多东西都可以上 NGA 看看，这段时间太忙了没有再整理，~~下次一定~~。
Kolla-Ansible 部署可以参阅我博客上的流水账 😂，（虽然没毕业但也基本没怎么上了xdd

**Comment by EarlWilliam** [comment]
确实是官方文档的妥帖的实践参考，对我来说很有价值。我有时候蛮怀疑官方文档的（......）
甚至看到了Yamibo的自动签到以及一万个管人...纯度很高呢？x
如果你也在鸟区的话，说不定还能6.0江湖再见。虽然那个时候大概是毕业季会很忙吧（（

**Comment by jckling** [comment]
在鸟区，回头可以约√

**Comment by EarlWilliam** [comment]
我全职业贼溜（广告发言仅供参考）欢迎找我课后辅导（.....）
神秘代码1050586002添加查看经典笑话（（

**Comment by jckling** [comment]
最近没时间玩但还是先加一个！我——来——了——
